WebApplication1/Controllers/Rapport_GeosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FestivalAPI.Data;
using FestivalAPI.Models;

using WebApplication1.ControllersAPI;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Newtonsoft.Json;

namespace WebApplication1.Controllers
{
    public class Rapport_GeosController : Controller
    {
        public IActionResult Rapport_Geo_Departement(int Id)
        {
            string Search = API.Instance.GetDepartementAsync(Id).Result.Nom;
            List<Rapport_Geo> rapport = (List<Rapport_Geo>)API.Instance.Rapport_Geo_DepartementAsync(Search).Result;

            return View(rapport);
        }

        public IActionResult Rapport_Geo_Region(int Id)
        {
            string Search = API.Instance.GetRegionAsync(Id).Result.Nom;
            List<Rapport_Geo> rapport = (List<Rapport_Geo>)API.Instance.Rapport_Geo_RegionAsync(Search).Result;

            return View(rapport);
        }

        public IActionResult Rapport_Geo_Pays(int Id)
        {
            string Search = API.Instance.GetPaysAsync(Id).Result.Nom;
            List<Rapport_Geo> rapport = (List<Rapport_Geo>)API.Instance.Rapport_Geo_PaysAsync(Search).Result;

            return View(rapport);
        }

        public IActionResult Rapport_Geo_Genre(int Id)
        {
            string Search = API.Instance.GetGenreAsync(Id).Result.Nom;
            List<Rapport_Geo> rapport = (List<Rapport_Geo>)API.Instance.Rapport_Geo_GenreAsync(Search).Result;

            return View(rapport);
        }

        public IActionResult Rapport_Geo_Departement_Graphe(int Id)
        {
            int Ido = (int)HttpContext.Session.GetInt32("ido");
            int IdF = API.Instance.GetOrganisateurAsync(Ido).Result.FestivalId;
            string Departement = API.Instance.GetDepartementAsync(Id).Result.Nom;

            List<Rapport_Geo> rapport = (List<Rapport_Geo>)API.Instance.Rapport_Geo_DepartementAsync(Departement).Result;
            List<string> Liste = new List<string>();
            List<int> count = (List<int>)API.Instance.Rapport_Geo_Count_DepartementAsync(IdF, Departement).Result;

            foreach (var elmt in rapport)
            {
                if (!Liste.Contains(elmt.Region))
                {
                    Liste.Add(elmt.Region);
                }
            }
            Liste.Reverse();
            string json1 = JsonConvert.SerializeObject(Liste);
            string json3 = JsonConvert.SerializeObject(count);

            ViewBag.Liste = json1;
            ViewBag.Nombre_Participants = json3;

            ViewBag.Rapport_Geo = rapport;

            return View();
        }

        public IActionResult Rapport_Geo_Region_Graphe(int Id)
        {
            int Ido = (int)HttpContext.Session.GetInt32("ido");
            int IdF = API.Instance.GetOrganisateurAsync(Ido).Result.FestivalId;
            string Region = API.Instance.GetRegionAsync(Id).Result.Nom;

            List<Rapport_Geo> rapport = (List<Rapport_Geo>)API.Instance.Rapport_Geo_RegionAsync(Region).Result;
            List<string> Liste = new List<string>(); ;
            List<int> count = (List<int>)API.Instance.Rapport_Geo_Count_RegionAsync(IdF, Region).Result;

            foreach (var elmt in rapport)
            {
                if (!Liste.Contains(elmt.Genre))
                {
                    Liste.Add(elmt.Genre);
                }
            }
            Liste.Reverse();
            string json1 = JsonConvert.SerializeObject(Liste);
            string json3 = JsonConvert.SerializeObject(count);

            ViewBag.Liste = json1;
            ViewBag.Nombre_Participants = json3;

            ViewBag.Rapport_Geo = rapport;

            return View();
        }

        public IActionResult Rapport_Geo_Pays_Graphe(int Id)
        {
            int Ido = (int)HttpContext.Session.GetInt32("ido");
            int IdF = API.Instance.GetOrganisateurAsync(Ido).Result.FestivalId;
            string Pays = API.Instance.GetPaysAsync(Id).Result.Nom;

            List<Rapport_Geo> rapport = (List<Rapport_Geo>)API.Instance.Rapport_Geo_PaysAsync(Pays).Result;
            List<string> Liste = new List<string>();
            List<int> count = (List<int>)API.Instance.Rapport_Geo_Count_PaysAsync(IdF, Pays).Result;

            foreach (var elmt in rapport)
            {
                if (!Liste.Contains(elmt.Region))
                {
                    Liste.Add(elmt.Region);
                }
            }

            Liste.Reverse();

            string json1 = JsonConvert.SerializeObject(Liste);
            string json3 = JsonConvert.SerializeObject(count);

            ViewBag.Liste = json1;
            ViewBag.Nombre_Participants = json3;

            ViewBag.Rapport_Geo = rapport;

            return View();
        }
        public IActionResult Index()
        {
            var Artistes = API.Instance.GetRegionsAsync().Result;

            return View(Artistes);
        }
        public IActionResult IndexPays()
        {
            var Artistes = API.Instance.GetPaysAsync().Result;

            return View(Artistes);
        }
        public IActionResult IndexDepartement()
        {
            var Artistes = API.Instance.GetDepartementsAsync().Result;

            return View(Artistes);
        }
    }
}

WebApplication1/Views/Rapport_Geos/Index.cshtml
@model IEnumerable<FestivalAPI.Models.Region>

@{
    ViewData["Title"] = "Index";
}

<h1>Liste des régions</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    <a asp-controller="Rapport_Geos" asp-action="Rapport_Geo_Region_Graphe" asp-route-id="@item.Id">Rapport geographique Region</a>
                </td>
            </tr>
        }
    </tbody>
</table>

WebApplication1/Views/Rapport_Geos/IndexDepartement.cshtml
@model IEnumerable<FestivalAPI.Models.Departement>

@{
    ViewData["Title"] = "Index";
    IEnumerable<FestivalAPI.Models.Festival> festivals = WebApplication1.ControllersAPI.API.Instance.GetFestivalsAsync().Result;
}

<h1>Liste des départements</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>

                <td>
                    <a asp-controller="Rapport_Geos" asp-action="Rapport_Geo_Departement_Graphe" asp-route-id="@item.Id">Rapport geographique Département</a>
                </td>
            </tr>
        }
    </tbody>
</table>

WebApplication1/Views/Rapport_Geos/IndexPays.cshtml
@model IEnumerable<FestivalAPI.Models.Pays>

@{
    ViewData["Title"] = "Index";
}

<h1>Liste des pays</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    <a asp-controller="Rapport_Geos" asp-action="Rapport_Geo_Pays_Graphe" asp-route-id="@item.Id">Rapport geographique Pays</a>
                </td>
            </tr>
        }
    </tbody>
</table>

WebApplication1/Views/Rapport_Geos/Rapport_Geo_Departement_Graphe.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@*@{
        ViewBag["Title"] = "For Region";
    }*@

<div class=" contenair-fluid section1 text-center ">
    <h1>Rapport Géographique (Departement)</h1>
</div>
<div class=" row container-fluid section1 text-center">
    <div class="col-md-12 text-center mb-3">
        <h2>caractéristique du graphe</h2>
        <p>Présentation générale et Variation des participations des festivaliers par département </p>
    </div>
</div>
<div class="row container-fluid section1 text-center">
    <div class="col-md-2">

    </div>
    <div class="col-md-8 mb-3">
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <canvas id="myChart" width="500" height="500"></canvas>
    </div>

    <div class="col-md-2">

    </div>
</div>

<script>
            var ctx = document.getElementById('myChart').getContext('2d');
            var v = @Html.Raw(@ViewBag.Liste);
            var ctx = document.getElementById('myChart').getContext('2d');
            var chart = new Chart(ctx, {
                // The type of chart we want to create
                type: 'bar',

                // The data for our dataset
                data: {
                    labels: @Html.Raw(@ViewBag.Liste) ,
                    datasets: [{
                        label: 'Inscription per Department',
                        backgroundColor: 'rgb(255, 99, 132)',
                        borderColor: 'rgb(255, 99, 132)',
                        data: @ViewBag.Nombre_Participants
                    }]
                },

                // Configuration options go here
                options: {}
            });
</script>

WebApplication1/Views/Rapport_Geos/Rapport_Geo_Pays_Graphe.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@*@{
        ViewBag["Title"] = "For Region";
    }*@

<div class=" contenair-fluid section1 text-center ">
    <h1>Rapport Géographique (Pays)</h1>
</div>
<div class=" row container-fluid section1 text-center">
    <div class="col-md-12 text-center mb-3">
        <h2>caractéristique du graphe</h2>
        <p>Présentation générale et Variation des participations des festivaliers par pays </p>
    </div>
</div>
<div class="row container-fluid section1 text-center">
    <div class="col-md-2">

    </div>
    <div class="col-md-8 mb-3">
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <canvas id="myChart" width="500" height="500"></canvas>
    </div>

    <div class="col-md-2">

    </div>
</div>

<script>
            var ctx = document.getElementById('myChart').getContext('2d');
            var v = @Html.Raw(@ViewBag.Liste);
            var ctx = document.getElementById('myChart').getContext('2d');
            var chart = new Chart(ctx, {
                // The type of chart we want to create
                type: 'bar',

                // The data for our dataset
                data: {
                    labels: @Html.Raw(@ViewBag.Liste) ,
                    datasets: [{
                        label: 'Inscription per Department',
                        backgroundColor: 'rgb(255, 99, 132)',
                        borderColor: 'rgb(255, 99, 132)',
                        data: @ViewBag.Nombre_Participants
                    }]
                },

                // Configuration options go here
                options: {}
            });
</script>

WebApplication1/Views/Rapport_Geos/Rapport_Geo_Region_Graphe.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@*@{
        ViewBag["Title"] = "For Region";
    }*@

<div class=" contenair-fluid section1 text-center ">
    <h1>Rapport Géographique (Région)</h1>
</div>
<div class=" row container-fluid section1 text-center">
    <div class="col-md-12 text-center mb-3">
        <h2>caractéristique du graphe</h2>
        <p>Présentation générale et Variation des participations des festivaliers par région </p>
    </div>
</div>
<div class="row container-fluid section1 text-center">
    <div class="col-md-2">

    </div>
    <div class="col-md-8 mb-3">
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <canvas id="myChart" width="500" height="500"></canvas>
    </div>

    <div class="col-md-2">

    </div>
</div>

<script>
            var ctx = document.getElementById('myChart').getContext('2d');
            var v = @Html.Raw(@ViewBag.Liste);
            var ctx = document.getElementById('myChart').getContext('2d');
            var chart = new Chart(ctx, {
                // The type of chart we want to create
                type: 'bar',

                // The data for our dataset
                data: {
                    labels: @Html.Raw(@ViewBag.Liste) ,
                    datasets: [{
                        label: 'Inscription per Region',
                        backgroundColor: 'rgb(255, 99, 132)',
                        borderColor: 'rgb(255, 99, 132)',
                        data: @ViewBag.Nombre_Participants
                    }]
                },

                // Configuration options go here
                options: {}
            });
</script>