WebApplication1/Controllers/Rapport_ActivitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FestivalAPI.Data;
using FestivalAPI.Models;

using WebApplication1.ControllersAPI;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Newtonsoft.Json;

namespace WebApplication1.Controllers
{
    public class Rapport_ActivitesController : Controller
    {
        public IActionResult Rapport_Activite_Region(string region)
        {

            List<Rapport_Activite> rapport = (List<Rapport_Activite>)API.Instance.Rapport_Activites_RegionAsync(region).Result;
            
            return View(rapport);
        }

        public IActionResult Rapport_Activite_Departement(string Departement)
        {

            List<Rapport_Activite> rapport = (List<Rapport_Activite>)API.Instance.Rapport_Activites_DepartementAsync(Departement).Result;

            return View(rapport);
        }

        public IActionResult Rapport_Activite_Festival(int FestivalId)
        {

            List<Rapport_Activite> rapport = (List<Rapport_Activite>)API.Instance.Rapport_Activites_FestivalAsync(FestivalId).Result;

            return View(rapport);
        }
        public ActionResult Rapport_Activite_Region_Graphe(int Id)
        {
            string region = API.Instance.GetRegionAsync(Id).Result.Nom;

            List<Rapport_Activite> rapport = (List<Rapport_Activite>)API.Instance.Rapport_Activites_RegionAsync(region).Result;
            List<int> List_Year = new List<int>();
            List<double> List_Somme = new List<double>();
            foreach (var elmt in rapport)
            {
                List_Year.Add(elmt.Annee);
                List_Somme.Add(elmt.Somme_Vente);
            }

            string json1 = JsonConvert.SerializeObject(List_Year);
            string json3 = JsonConvert.SerializeObject(List_Somme);

            ViewBag.Liste_Year = json1;
            ViewBag.Liste_Somme = json3;

            ViewBag.Rapport_Activite = rapport;

            return View();
        }

        public IActionResult Rapport_Activite_Departement_Graphe(int Id)
        {
            string Departement = API.Instance.GetDepartementAsync(Id).Result.Nom;

            List<Rapport_Activite> rapport = (List<Rapport_Activite>)API.Instance.Rapport_Activites_DepartementAsync(Departement).Result;
            List<int> List_Year = new List<int>();
            List<double> List_Somme = new List<double>();
            foreach (var elmt in rapport)
            {
                List_Year.Add(elmt.Annee);
                List_Somme.Add(elmt.Somme_Vente);
            }

            string json1 = JsonConvert.SerializeObject(List_Year);
            string json3 = JsonConvert.SerializeObject(List_Somme);

            ViewBag.Liste_Year = json1;
            ViewBag.Liste_Somme = json3;

            ViewBag.Rapport_Activite = rapport;

            return View();
        }

        public IActionResult Rapport_Activite_Festival_Graphe(int Id)
        {

            List<Rapport_Activite> rapport = (List<Rapport_Activite>)API.Instance.Rapport_Activites_FestivalAsync(Id).Result;
            List<int> List_Year = new List<int>();
            List<double> List_Somme = new List<double>();
            foreach (var elmt in rapport)
            {
                List_Year.Add(elmt.Annee);
                List_Somme.Add(elmt.Somme_Vente);
            }

            string json1 = JsonConvert.SerializeObject(List_Year);
            string json3 = JsonConvert.SerializeObject(List_Somme);

            ViewBag.Liste_Year = json1;
            ViewBag.Liste_Somme = json3;

            ViewBag.Rapport_Activite = rapport;

            return View();
        }

        public IActionResult Index()
        {
            var Artistes = API.Instance.GetRegionsAsync().Result;

            return View(Artistes);
        }
        public IActionResult IndexFestival()
        {
            var Artistes = API.Instance.GetFestivalsAsync().Result;

            return View(Artistes);
        }
        public IActionResult IndexDepartement()
        {
            var Artistes = API.Instance.GetDepartementsAsync().Result;

            return View(Artistes);
        }
    }
}

WebApplication1/Views/Rapport_Activites/Graphe_Region.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag["Title"] = "For Region";
}

<div class=" contenair-fluid section1 text-center ">
    <h1>Graphe de variation par région</h1>
</div>
<div class=" row container-fluid section1 text-center">
    <div class="col-md-12 text-center mb-3">
        <h2>caractéristique du graphe</h2>
        <p>Variation des participations des festivaliers par région </p>
    </div>
</div>
<div class="row container-fluid section1 text-center">
    <div class="col-md-2">

    </div>
    <div class="col-md-8 mb-3">
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <canvas id="myChart" width="500" height="500"></canvas>
    </div>
    <div class="col-md-2">

    </div>
</div>
<script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var v = @Html.Raw(@ViewBag.List_Year);
    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'line',

        // The data for our dataset
        data: {
            labels: @ViewBag.List_Somme ,
            datasets: [{
                label: 'Population croissance per year',
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
                data: @ViewBag.List_Somme
            }]
        },

        // Configuration options go here
        options: {}
    });
</script>

WebApplication1/Views/Rapport_Activites/Index.cshtml
@model IEnumerable<FestivalAPI.Models.Region>

@{
    ViewData["Title"] = "Index";
}

<h1>Liste des régions</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    <a asp-controller="Rapport_Activites" asp-action="Rapport_Activite_Region_Graphe" asp-route-id="@item.Id">Rapport Activité Region</a>
                </td>
            </tr>
        }
    </tbody>
</table>

WebApplication1/Views/Rapport_Activites/IndexDepartement.cshtml
@model IEnumerable<FestivalAPI.Models.Departement>

@{
    ViewData["Title"] = "Index";
}

<h1>Liste des départements</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    <a asp-controller="Rapport_Activites" asp-action="Rapport_Activite_Departement_Graphe" asp-route-id="@item.Id">Rapport Activité Region</a>
                </td>
            </tr>
        }
    </tbody>
</table>

WebApplication1/Views/Rapport_Activites/IndexFestival.cshtml
@model IEnumerable<FestivalAPI.Models.Festival>

@{
    ViewData["Title"] = "Index";
}

<h1>Liste des festivals</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    <a asp-controller="Rapport_Activites" asp-action="Rapport_Activite_Festival_Graphe" asp-route-id="@item.IdF">Rapport Activité Region</a>
                </td>
            </tr>
        }
    </tbody>
</table>

WebApplication1/Views/Rapport_Activites/Rapport_Activite_Departement_Graphe.cshtml
<div class=" contenair-fluid section1 text-center ">
    <h1>Graphe de variation par département</h1>
</div>
<div class=" row container-fluid section1 text-center">
    <div class="col-md-12 text-center mb-3">
        <h2>caractéristique du graphe</h2>
        <p>Variation des participations des festivaliers par région </p>
    </div>
</div>
<div class="row container-fluid section1 text-center">
    <div class="col-md-2">

    </div>
    <div class="col-md-8 mb-3">
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <canvas id="myChart" width="500" height="500"></canvas>
    </div>
    <div class="col-md-2">

    </div>
</div>
<script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var v = @Html.Raw(@ViewBag.Liste_Year);
    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'line',

        // The data for our dataset
        data: {
            labels: @Html.Raw(@ViewBag.Liste_Year) ,
            datasets: [{
                label: 'Evolution inscription money per department',
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
                data: @ViewBag.Liste_Somme
            }]
        },

        // Configuration options go here
        options: {}
    });
</script>

WebApplication1/Views/Rapport_Activites/Rapport_Activite_Festival_Graphe.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@*@{
        ViewBag["Title"] = "For Region";
    }*@

<div class=" contenair-fluid section1 text-center ">
    <h1>Graphe de variation général</h1>
</div>
<div class=" row container-fluid section1 text-center">
    <div class="col-md-12 text-center mb-3">
        <h2>caractéristique du graphe</h2>
        <p>Variation des participations des festivaliers par région </p>
    </div>
</div>
<div class="row container-fluid section1 text-center">
    <div class="col-md-2">

    </div>
    <div class="col-md-8 mb-3">
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <canvas id="myChart" width="500" height="500"></canvas>
    </div>
    <div class="col-md-2">

    </div>
</div>
<script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var v = @Html.Raw(@ViewBag.Liste_Year);
    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'line',

        // The data for our dataset
        data: {
            labels: @Html.Raw(@ViewBag.Liste_Year) ,
            datasets: [{
                label: 'Evolution inscription money',
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
                data: @ViewBag.Liste_Somme
            }]
        },

        // Configuration options go here
        options: {}
    });
</script>

WebApplication1/Views/Rapport_Activites/Rapport_Activite_Region_Graphe.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@*@{
    ViewBag["Title"] = "For Region";
}*@

<div class=" contenair-fluid section1 text-center ">
    <h1>Graphe de variation par région</h1>
</div>
<div class=" row container-fluid section1 text-center">
    <div class="col-md-12 text-center mb-3">
        <h2>caractéristique du graphe</h2>
        <p>Variation des participations des festivaliers par région </p>
    </div>
</div>
<div class="row container-fluid section1 text-center">
    <div class="col-md-2">

    </div>
    <div class="col-md-8 mb-3">
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <canvas id="myChart" width="500" height="500"></canvas>
    </div>
    <div class="col-md-2">

    </div>
</div>
<script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var v = @Html.Raw(@ViewBag.Liste_Year);
    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'line',

        // The data for our dataset
        data: {
            labels: @Html.Raw(@ViewBag.Liste_Year) ,
            datasets: [{
                label: 'Evolution inscription money per region',
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
                data: @ViewBag.Liste_Somme
            }]
        },

        // Configuration options go here
        options: {}
    });
</script>