WebApplication1/Controllers/AmisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FestivalAPI.Data;
using FestivalAPI.Models;

using WebApplication1.ControllersAPI;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace WebApplication1.Controllers
{
        public class AmisController : Controller
        {
            /* private readonly APIContext _context;



             public AmisController(APIContext context)
             {
                 _context = context;
             }*/



            // GET: Ami
            public IActionResult Index()
            {

        
            if (HttpContext.Session.GetInt32("idf") == null)
            {
                return null;
            }
            else
            {
                           int FestivalierId = (int)HttpContext.Session.GetInt32("idf");
        var Amis = API.Instance.GetAmitiésAsync().Result.Where(f => f.Accepted && (f.AmiReceveur == FestivalierId || f.AmiDemandeur == FestivalierId));

            return View(Amis);
    }

 


        }
        



        // GET: Ami/Details/5
        public IActionResult Details(int? id)
            {
                /*if (id == null)
                {
                    return NotFound();
                }



                var Ami = await _context.Ami
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (Ami == null)
                {
                    return NotFound();
                }



                return View(Ami);*/



                if (id == null)
                {
                    return null;
                }
                return View(API.Instance.GetAmitiéAsync(id).Result);
            }



            // GET: Ami/Create
            public IActionResult Create()
            {
                return View();
            }



        // POST: Ami/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public IActionResult Create(Ami ami)
        {
            int drapeau = 0;
            IEnumerable<Ami> amitiés = API.Instance.GetAmitiésAsync().Result;
            foreach (var item in amitiés)
            {
                if (item.AmiDemandeur == ami.AmiDemandeur && item.AmiReceveur == ami.AmiReceveur)
                {
                    drapeau++;
                }
            }

            if (ModelState.IsValid && drapeau == 0)
            {
                var URI = API.Instance.AjoutAmiAsync(ami);
                return Redirect("/Festivals/Festivaliers");
            }
            else if (drapeau != 0)
            {
                return Redirect("/Festivals/Festivaliers");
            }
             return Redirect("/Festivals/Festivaliers");
        }
        // POST: Ami/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Create(int? id)
        {
            int drapeau = 0;
            Ami ami = new Ami();
            ami.AmiDemandeur= (int)HttpContext.Session.GetInt32("idf");
            if (id==0)
            {
                return null;
            }ami.AmiReceveur = (int)id;
            ami.Accepted = false;
            ami.Vue= false;
            IEnumerable<Ami> amitiés = API.Instance.GetAmitiésAsync().Result;
            foreach (var item in amitiés)
            {
                if (item.AmiDemandeur == ami.AmiDemandeur && item.AmiReceveur == ami.AmiReceveur)
                {
                    ami=item;
                    var URI = API.Instance.ModifAmiAsync(ami);
                    return Redirect("/Festivals/Festivaliers");
                }
            }

            if (ModelState.IsValid && drapeau == 0)
            {
                var URI = API.Instance.AjoutAmiAsync(ami);
                return Redirect("/Festivals/Festivaliers");
            }
            else if (drapeau != 0)
            {
                return Redirect("/Festivals/Festivaliers");
            }
            return Redirect("/Festivals/Festivaliers");
        }

        // GET: Ami/Edit/5
        public IActionResult Edit(int? id)
            {

                if (id == null)
                {
                    return null;
                }
                return View(API.Instance.GetAmitiéAsync(id).Result);
            }



            // POST: Ami/Edit/5
            // To protect from overposting attacks, enable the specific properties you want to bind to, for 
            // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
        public IActionResult Edit(Ami ami)
        {
            int drapeau = 0;
            IEnumerable<Ami> amitiés = API.Instance.GetAmitiésAsync().Result;
            foreach (var item in amitiés)
            {
                if (item.AmiDemandeur == ami.AmiDemandeur && item.AmiReceveur == ami.AmiReceveur)
                {
                    drapeau++;
                }
            }

            if (ModelState.IsValid && drapeau == 0)
            {
                var URI = API.Instance.ModifAmiAsync(ami);
                return RedirectToAction(nameof(Index));
            }
            else if (drapeau != 0)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(ami);
        }



        // GET: Ami/Delete/5
        public IActionResult Delete(int? id)
            {
                /*if (id == null)
                {
                    return NotFound();
                }




                var Ami = await _context.Ami
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (Ami == null)
                {
                    return NotFound();
                }
                return View(Ami);
                */
                if (id == null)
                {
                    return null;
                }
                 return Redirect("/Festivals/Festivaliers");

        }



            // POST: Ami/Delete/5
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public IActionResult DeleteConfirmed(int id)
            {
                var URI = API.Instance.SupprAmiAsync(id);
                 return Redirect("/Festivals/Festivaliers");
            }

       
        public IActionResult Partage(int id)
        {
             if (HttpContext.Session.GetInt32("idf") == null)
            {
                return null;
            }
            else
            {

                 int FestivalierId = (int)HttpContext.Session.GetInt32("idf");


                Ami ami = (Ami)API.Instance.GetAmitiéAsync(FestivalierId, id).Result;

                if (ami != null)
                {

                    IEnumerable<Favoris> favoris = API.Instance.GetFavorisAsync().Result.Where(s => s.FestivalierId == FestivalierId && s.Like == true);

                    List<Artiste> artistes = new List<Artiste>();

                    foreach (var item in favoris)
                    {
                        Artiste artiste = new Artiste();

                        artiste = (Artiste)API.Instance.GetArtisteAsync(item.ArtisteId).Result;

                        artistes.Add(artiste);
                    }


                    ViewBag.Artistes = artistes;
                }
                return View();
            }
           
        }

        public IActionResult Consult(int id)
        {
            if (HttpContext.Session.GetInt32("idf") == null)
            {
                return null;
            }
            else
            {

                int FestivalierId = (int)HttpContext.Session.GetInt32("idf");


                Ami ami = (Ami)API.Instance.GetAmitiéAsync(FestivalierId, id).Result;

                if (ami != null)
                {

                    IEnumerable<Favoris> favoris = API.Instance.GetFavorisAsync().Result.Where(s => s.FestivalierId == id && s.Like == true);

                    List<Artiste> artistes = new List<Artiste>();

                    foreach (var item in favoris)
                    {
                        Artiste artiste = new Artiste();

                        artiste = (Artiste)API.Instance.GetArtisteAsync(item.ArtisteId).Result;

                        artistes.Add(artiste);
                    }

                    ViewBag.Artistes = artistes;
                }
                return View();
            }
        }

        /*private bool AmiExists(int id)
        {
            return _context.Ami.Any(e => e.Id == id);
        }*/
    }
}

WebApplication1/Controllers/ScenesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FestivalAPI.Data;
using FestivalAPI.Models;

using WebApplication1.ControllersAPI;

namespace WebApplication1.Controllers
{
        public class ScenesController : Controller
        {
            /* private readonly APIContext _context;



             public ScenesController(APIContext context)
             {
                 _context = context;
             }*/



            // GET: Scene
            public IActionResult Index()
            {
                //return View(await _context.Scene.Include("Links").ToListAsync());



                //IEnumerable<Scene> Scenes = API.Instance.GetScenesAsync().Result;
                //return View(Scenes);
                var scenes = API.Instance.GetScenesAsync().Result;








                return View(scenes);
            }




            // GET: Scene/Details/5
            public IActionResult Details(int? id)
            {
                /*if (id == null)
                {
                    return NotFound();
                }



                var Scene = await _context.Scene
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (Scene == null)
                {
                    return NotFound();
                }



                return View(Scene);*/



                if (id == null)
                {
                    return null;
                }
                return View(API.Instance.GetSceneAsync(id).Result);
            }



            // GET: Scene/Create
            public IActionResult Create()
            {
                return View();
            }



            // POST: Scene/Create
            // To protect from overposting attacks, enable the specific properties you want to bind to, for 
            // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult Create([Bind("IdS,Nom,Adresse,Capacite,Accessibilite,LieuId")] Scene scene)
            {
                int drapeau = 0;
                IEnumerable<Scene> scenes = API.Instance.GetScenesAsync().Result;
                foreach (var item in scenes)
                {
                    if (item.Nom == scene.Nom)
                    {
                        drapeau++;
                    }
                }



                if (ModelState.IsValid && drapeau == 0)
                {
                    var URI = API.Instance.AjoutSceneAsync(scene);
                    return RedirectToAction(nameof(Index));
                }
                else if (drapeau != 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                return View(scene);
            }



            // GET: Scene/Edit/5
            public IActionResult Edit(int? id)
            {
                /*if (id == null)
                {
                    return NotFound();
                }



                var Scene = await _context.Scene.FindAsync(id);
                if (Scene == null)
                {
                    return NotFound();
                }
                return View(Scene);*/



                if (id == null)
                {
                    return null;
                }
                return View(API.Instance.GetSceneAsync(id).Result);



            }



            // POST: Scene/Edit/5
            // To protect from overposting attacks, enable the specific properties you want to bind to, for 
            // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult Edit(int id, [Bind("IdS,Nom,Adresse,Capacite,Accessibilite,LieuId")] Scene scene)
            {
                /*if (id != Scene.Id)
                {
                    return NotFound();
                }



                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(Scene);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!SceneExists(Scene.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(Scene);*/
                if (id != scene.IdS)
                {
                    return NotFound();
                }





                if (ModelState.IsValid)
                {
                    var URI = API.Instance.ModifSceneAsync(scene);
                    return RedirectToAction(nameof(Index));
                }
                return View(scene);
            }



            // GET: Scene/Delete/5
            public IActionResult Delete(int? id)
            {
                /*if (id == null)
                {
                    return NotFound();
                }




                var Scene = await _context.Scene
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (Scene == null)
                {
                    return NotFound();
                }
                return View(Scene);
                */
                if (id == null)
                {
                    return null;
                }
                return View(API.Instance.GetSceneAsync(id).Result);



            }



            // POST: Scene/Delete/5
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public IActionResult DeleteConfirmed(int id)
            {
                /*
                var Scene = await _context.Scene.FindAsync(id);
                _context.Scene.Remove(Scene);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                */



                var URI = API.Instance.SupprSceneAsync(id);
                return RedirectToAction(nameof(Index));



            }



            /*private bool SceneExists(int id)
            {
                return _context.Scene.Any(e => e.Id == id);
            }*/
        }
    }

WebApplication1/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{ 
    FestivalAPI.Models.Festivalier festivalier = new FestivalAPI.Models.Festivalier();
    FestivalAPI.Models.Festival festival = new FestivalAPI.Models.Festival();
    FestivalAPI.Models.Organisateur organisateur = new FestivalAPI.Models.Organisateur();
}

@if (HttpContextAccessor.HttpContext.Session.GetInt32("idf") != null)
{
    festivalier = WebApplication1.ControllersAPI.API.Instance.GetFestivalierAsync((int)HttpContextAccessor.HttpContext.Session.GetInt32("idf")).Result;
    festival = WebApplication1.ControllersAPI.API.Instance.GetFestivalAsync(festivalier.FestivalId).Result;

}

@if (HttpContextAccessor.HttpContext.Session.GetInt32("ido") != null)
{
     organisateur = WebApplication1.ControllersAPI.API.Instance.GetOrganisateurAsync((int)HttpContextAccessor.HttpContext.Session.GetInt32("ido")).Result;

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Festi'Normandie</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Festival Normandie</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Festivals
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-area="" asp-controller="Festivals" asp-action="Index">Voir festivals</a>
                            @if (@HttpContextAccessor.HttpContext.Session.GetString("category") == "Organisateur")
                            {
                                <a class="dropdown-item" asp-area="" asp-controller="Hebergements" asp-action="Index">Gérer hebergements</a>
                            }

                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Artistes
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-area="" asp-controller="Artistes" asp-action="Index">Voir artistes</a>
                            @if ((HttpContextAccessor.HttpContext.Session.GetInt32("idf") != null && HttpContextAccessor.HttpContext.Session.GetString("category").Equals("Festivalier")))
                            {
                                <a class="dropdown-item" asp-area="" asp-controller="Artistes" asp-action="ListeFavoris">liste des favoris</a>
                            }
                            @if (@HttpContextAccessor.HttpContext.Session.GetString("category") == "Organisateur")
                            {
                                <a class="dropdown-item" asp-area="" asp-controller="Festivals" asp-action="AjoutArtiste">Ajouter artiste</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Scenes" asp-action="Index">Gérer Scène</a>

                            }
                        </div>
                    </li>
                    @if ((HttpContextAccessor.HttpContext.Session.GetInt32("idf") != null && HttpContextAccessor.HttpContext.Session.GetString("category").Equals("Festivalier")))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Ami
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Festivals" asp-action="Festivaliers">Participants</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Festivals" asp-action="Demandes">Invitations</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Amis" asp-action="Index">Liste des amis</a>
                            </div>
                        </li>
                    }
                    @if (@HttpContextAccessor.HttpContext.Session.GetString("category") == "Organisateur")
                    {
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Festival_Artiste" asp-action="Programme">Programmation</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @festivalier.Pseudo
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Rapport_Activites" asp-action="Index">Rapport des activités par région</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Rapport_Activites" asp-action="IndexDepartement">Rapport des activités par département</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Rapport_Activites" asp-action="IndexFestival">Rapport des activités par festival</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Rapport_Geos" asp-action="Index">Rapport géographique par régions</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Rapport_Geos" asp-action="IndexDepartement">Rapport géographique par département</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Rapport_Geos" asp-action="IndexPays">Rapport géographique par pays</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Rapport_Temps" asp-action="Rapport_Temps_Festival_Graphe">Rapport temps par festival</a>
                            </div>
                        </li>

                    }

                </ul>
                @if ((HttpContextAccessor.HttpContext.Session.GetInt32("idf") != null && HttpContextAccessor.HttpContext.Session.GetString("category").Equals("Festivalier") ))
                {

                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @festivalier.Pseudo
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">Vous participez à @festival.Nom</a>
                            @if (festivalier.IsPublished)
                            {
                                <a class="dropdown-item" asp-area="" asp-controller="Festivaliers" asp-action="Depublier">Depublier</a>
                            }
                            else
                            {
                                <a class="dropdown-item" asp-area="" asp-controller="Festivaliers" asp-action="Publier">Publier</a>
                            }
                            <a class="dropdown-item" asp-area="" asp-controller="Connexion" asp-action="Deconnexion">Se déconnecter</a>
                        </div>
                    </div>

                }
                else if (HttpContextAccessor.HttpContext.Session.GetInt32("ido") != null && HttpContextAccessor.HttpContext.Session.GetString("category").Equals("Organisateur"))
                {
                    <a class="btn btn-primary" asp-area="" asp-controller="Connexion" asp-action="Deconnexion">Se déconnecter</a>


                }
                else
                {
                    <a class="btn btn-primary" asp-area="" asp-controller="Connexion" asp-action="ConnexionFestivalier">Se Connecter</a>
                }
                <form class="form-inline my-2 my-lg-0" method="get" asp-controller="Festivals" asp-action="Index">
                    <input type="text" class="form-control" placeholder="Search for a Festival" name="searchString" value="@ViewData["searchString"]">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>


            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Festi'Normandie
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>