WebApplication1/Controllers/FestivalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FestivalAPI.Data;
using FestivalAPI.Models;
using WebApplication1.ControllersAPI;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace WebApplication1.Controllers
{
    public class FestivalsController : Controller
    {
        private FestivalAPI.Data.SendMail sendMail;
        
        /* private readonly APIContext _context;

 

         public FestivalsController(APIContext context)
         {
             _context = context;
         }*/



        // GET: Festival
        /* public IActionResult Index()
         {

             var festivals = API.Instance.GetFestivalsAsync().Result;

             return View(festivals);
         }*/
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Index(string searchString)
        {
            IEnumerable<Artiste> artistes = API.Instance.GetArtistesAsync().Result;
            IEnumerable<Scene> scenes = API.Instance.GetScenesAsync().Result;
            IEnumerable<Festival> festival = API.Instance.GetFestivalsAsync().Result;
            IEnumerable<Lieu> communes = API.Instance.GetLieuxAsync().Result;
            List<Festival> festivals = new List<Festival>();



            if (!String.IsNullOrEmpty(searchString))
            {
                //var rech = artistes.Where(e => e.Nom.Contains(searchString)).Select(e => e.Artiste_Festival);
                var fes1 = festival.Where(e => e.Nom.Contains(searchString));
                var fes2 = communes.Where(e => e.Commune.Contains(searchString)).Select(e => e.Festivals);
                var fes3 = artistes.Where(e => e.Nom.Contains(searchString)).Select(e => e.Festival_Artistes);
                var fes4 = scenes.Where(e => e.Nom.Contains(searchString)).Select(e => e.Festival_Artistes);
                
                foreach (var nomfes in fes1)
                {
                    var NomFest = API.Instance.GetFestivalAsync(nomfes.IdF).Result;
                    festivals.Add(NomFest);
                }
                foreach (var communefes in fes2)
                {
                    foreach (var idcommune in communefes)
                    {
                        var commune = API.Instance.GetLieuAsync(idcommune.IdF).Result;
                        var Lieu = API.Instance.GetFestivalAsync(commune.IdL).Result;
                        festivals.Add(Lieu);
                    }
                }
                foreach (var artistefes in fes3)
                {
                    foreach (var artiste in artistefes)
                    {
                        var NomArtiste = API.Instance.GetFestivalAsync(artiste.FestivalId).Result;
                        festivals.Add(NomArtiste);
                    }
                }
                foreach (var scenefes in fes4)
                {
                    foreach (var scene in scenefes)
                    {
                        var NomScene = API.Instance.GetFestivalAsync(scene.FestivalId).Result;
                        festivals.Add(NomScene);
                    }
                }


                return View(festivals);
            }
            else
            {
                IEnumerable<Festival> festivalss = API.Instance.GetFestivalsAsync().Result;
                return View(festivalss);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Index(string lieu, string artiste, string style)
        {
            //return View(await _context.Region.Include("Links").ToListAsync());

            //IEnumerable<Region> regions = API.Instance.GetRegionsAsync().Result;
            //return View(regions);
            var lieux = from m in API.Instance.GetLieuxAsync().Result
                          select m;
            var artistes = from m in API.Instance.GetArtistesAsync().Result
                        select m;
            var styles = from m in API.Instance.GetArtistesAsync().Result
                           select m;
            ICollection<Festival_Artiste> festival_Artistes = new List<Festival_Artiste>();
            ICollection<Festival> festivals = new List<Festival>();
            ICollection<Artiste> artistes2 = new List<Artiste>();

            if (!String.IsNullOrEmpty(lieu))
            {
                lieux = lieux.Where(s => s.Commune.Contains(lieu));
                foreach (var unlieu in lieux)
                {
                    foreach (var scene in unlieu.Scenes)
                    {
                        Scene scene1 = API.Instance.GetSceneAsync(scene.FestivalId).Result;
                        foreach(var festivalartiste in scene1.Festival_Artistes)
                        {
                            if (!festival_Artistes.Contains(festivalartiste))
                                festival_Artistes.Add(festivalartiste);
                        }
                    }

                }
            }

            if (!String.IsNullOrEmpty(artiste))
            {
                artistes = artistes.Where(s => s.Nom.Contains(artiste));
                foreach (var art in artistes)
                {
                    Artiste artist = API.Instance.GetArtisteAsync(art.FestivalId).Result;
                    foreach (var festivalartiste in artist.Festival_Artistes)
                    {
                        if (!festival_Artistes.Contains(festivalartiste))
                            festival_Artistes.Add(festivalartiste);
                    }
                }
            }

            

            if (!String.IsNullOrEmpty(style))
            {
                styles = styles.Where(s => s.Nom.Contains(style));
                foreach (var sty in styles)
                {
                    artistes2.Add(API.Instance.GetArtisteAsync((int)sty.FestivalId).Result);
                    foreach (var art in artistes2)
                    {
                        Artiste artist = API.Instance.GetArtisteAsync(art.FestivalId).Result;
                        foreach (var festivalartiste in artist.Festival_Artistes)
                        {
                            if (!festival_Artistes.Contains(festivalartiste))
                                festival_Artistes.Add(festivalartiste);
                        }
                    }
                }
            }
            return View(festival_Artistes);
        }


        // GET: Festival/Details/5
        public IActionResult Details(int? id)
        {
            /*if (id == null)
            {
                return NotFound();
            }

 

            var Festival = await _context.Festival
                .FirstOrDefaultAsync(m => m.Id == id);
            if (Festival == null)
            {
                return NotFound();
            }

 

            return View(Festival);*/



            if (id == null)
            {
                return null;
            }
            return View(API.Instance.GetFestivalAsync(id).Result);
        }



        // GET: Festival/Create
        public IActionResult Create()
        {
            return View();
        }



        // POST: Festival/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("IdF,Nom,Logo,Descriptif,Date_Debut,Date_Fin,LieuId")] Festival festival, IFormFile file, [FromServices] IHostingEnvironment hostingEnvironment)
        
        {
            int taillemax = 2097152;

            List<String> extensionsvalides = new List<String>();
            List<String> strcut = new List<String>();
            extensionsvalides.Add(".jpg");
            extensionsvalides.Add(".jpeg");
            extensionsvalides.Add(".gif");
            extensionsvalides.Add(".png");
            extensionsvalides.Add(".jfif");
            string fileNamtre = file.FileName;

            string fileName = "img/festivals/" + festival.Nom;
            string extension = Path.GetExtension(file.FileName);
            string chemin = fileName + extension.ToLower();
            if (file.Length < taillemax && extensionsvalides.Contains(extension))
            {
                using (FileStream fileStream = System.IO.File.Create("wwwroot/" + chemin))
                {
                    file.CopyTo(fileStream);
                    fileStream.Flush();
                }
                festival.Logo = chemin;



                int drapeau = 0;
                IEnumerable<Festival> Festivals = API.Instance.GetFestivalsAsync().Result;
                foreach (var item in Festivals)
                {
                    if (item.Nom == festival.Nom)
                    {
                        drapeau++;
                    }
                }

                if (ModelState.IsValid && drapeau == 0)
                {
                    var URI = API.Instance.AjoutFestivalAsync(festival);
                    return RedirectToAction(nameof(Index));
                }
                else if (drapeau != 0)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(festival);
        }



        // GET: Festival/Edit/5
        public IActionResult Edit()
        {
            if (HttpContext.Session.GetInt32("ido") == null)
            {
                return null;
            }
            Organisateur organisateur = API.Instance.GetOrganisateurAsync((int)HttpContext.Session.GetInt32("ido")).Result;
            Festival festival = API.Instance.GetFestivalAsync(organisateur.FestivalId).Result;
            if (festival == null)
            {
                return null;

WebApplication1/Controllers/ScenesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FestivalAPI.Data;
using FestivalAPI.Models;

using WebApplication1.ControllersAPI;

namespace WebApplication1.Controllers
{
        public class ScenesController : Controller
        {
            /* private readonly APIContext _context;



             public ScenesController(APIContext context)
             {
                 _context = context;
             }*/



            // GET: Scene
            public IActionResult Index()
            {
                //return View(await _context.Scene.Include("Links").ToListAsync());



                //IEnumerable<Scene> Scenes = API.Instance.GetScenesAsync().Result;
                //return View(Scenes);
                var scenes = API.Instance.GetScenesAsync().Result;








                return View(scenes);
            }




            // GET: Scene/Details/5
            public IActionResult Details(int? id)
            {
                /*if (id == null)
                {
                    return NotFound();
                }



                var Scene = await _context.Scene
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (Scene == null)
                {
                    return NotFound();
                }



                return View(Scene);*/



                if (id == null)
                {
                    return null;
                }
                return View(API.Instance.GetSceneAsync(id).Result);
            }



            // GET: Scene/Create
            public IActionResult Create()
            {
                return View();
            }



            // POST: Scene/Create
            // To protect from overposting attacks, enable the specific properties you want to bind to, for 
            // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult Create([Bind("IdS,Nom,Adresse,Capacite,Accessibilite,LieuId")] Scene scene)
            {
                int drapeau = 0;
                IEnumerable<Scene> scenes = API.Instance.GetScenesAsync().Result;
                foreach (var item in scenes)
                {
                    if (item.Nom == scene.Nom)
                    {
                        drapeau++;
                    }
                }



                if (ModelState.IsValid && drapeau == 0)
                {
                    var URI = API.Instance.AjoutSceneAsync(scene);
                    return RedirectToAction(nameof(Index));
                }
                else if (drapeau != 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                return View(scene);
            }



            // GET: Scene/Edit/5
            public IActionResult Edit(int? id)
            {
                /*if (id == null)
                {
                    return NotFound();
                }



                var Scene = await _context.Scene.FindAsync(id);
                if (Scene == null)
                {
                    return NotFound();
                }
                return View(Scene);*/



                if (id == null)
                {
                    return null;
                }
                return View(API.Instance.GetSceneAsync(id).Result);



            }



            // POST: Scene/Edit/5
            // To protect from overposting attacks, enable the specific properties you want to bind to, for 
            // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult Edit(int id, [Bind("IdS,Nom,Adresse,Capacite,Accessibilite,LieuId")] Scene scene)
            {
                /*if (id != Scene.Id)
                {
                    return NotFound();
                }



                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(Scene);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!SceneExists(Scene.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(Scene);*/
                if (id != scene.IdS)
                {
                    return NotFound();
                }





                if (ModelState.IsValid)
                {
                    var URI = API.Instance.ModifSceneAsync(scene);
                    return RedirectToAction(nameof(Index));
                }
                return View(scene);
            }



            // GET: Scene/Delete/5
            public IActionResult Delete(int? id)
            {
                /*if (id == null)
                {
                    return NotFound();
                }




                var Scene = await _context.Scene
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (Scene == null)
                {
                    return NotFound();
                }
                return View(Scene);
                */
                if (id == null)
                {
                    return null;
                }
                return View(API.Instance.GetSceneAsync(id).Result);



            }



            // POST: Scene/Delete/5
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public IActionResult DeleteConfirmed(int id)
            {
                /*
                var Scene = await _context.Scene.FindAsync(id);
                _context.Scene.Remove(Scene);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                */



                var URI = API.Instance.SupprSceneAsync(id);
                return RedirectToAction(nameof(Index));



            }



            /*private bool SceneExists(int id)
            {
                return _context.Scene.Any(e => e.Id == id);
            }*/
        }
    }

WebApplication1/Views/Scenes/Delete.cshtml
@model FestivalAPI.Models.Scene

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Scene</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacite)
        </dt>
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Accessibilite)
        </dt>
        
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdS" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication1/Views/Scenes/Details.cshtml
@model FestivalAPI.Models.Scene

@{
    ViewData["Title"] = "Details";

}

<h1>Details</h1>

<div>
    <h4>Scene</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Accessibilite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Accessibilite)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdS">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication1/Views/Scenes/Edit.cshtml
@model FestivalAPI.Models.Scene
@{
    ViewData["Title"] = "Edit";

    IEnumerable<FestivalAPI.Models.Lieu> lieux = WebApplication1.ControllersAPI.API.Instance.GetLieuxAsync().Result;

    bool vrai = true;
    bool faux = false;
}

<h1>Edit</h1>

<h4>Scene</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdS" />
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacite" class="control-label"></label>
                <input asp-for="Capacite" type="number" class="form-control" />
                <span asp-validation-for="Capacite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Accessibilite" class="control-label">Accessible aux personnes handicapées</label>
                <select asp-for="Accessibilite" class="form-control">

                    <option value="@vrai">oui</option>
                    <option value="@faux">non</option>
                </select>
                <span asp-validation-for="Accessibilite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LieuId" class="control-label">Sélectionnez une date</label>
                <select class="form-control" asp-for="LieuId">
                    <option value="">Choisissez une option</option>
                    @foreach (var it in lieux)
                    {
                        <option value="@it.IdL">
                            @it.Commune
                        </option>
                    }
                </select>
                <span asp-validation-for="LieuId" class="text-danger"></span>
            </div>



            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>


</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/Scenes/Index.cshtml
@model IEnumerable<FestivalAPI.Models.Scene>

@{
    ViewData["Title"] = "Index";
    IEnumerable<FestivalAPI.Models.Lieu> Lieux = WebApplication1.ControllersAPI.API.Instance.GetLieuxAsync().Result;

}

<h1>Liste des Scènes</h1>

<p>
    <a asp-area="" asp-controller="Festivals" asp-action="AjoutScene">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
        <tr>
            <th>
                Nom de la scène
            </th>
            <th>
                Adresse
            </th>
            <th>
                Capacité
            </th>
            <th>
                Accessibilité
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adresse)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Capacite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Accessibilite)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdS">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.IdS">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.IdS">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>